import React from 'react';

function getInstallHint(isIOS, deferredPrompt) {
  if (isIOS) {
    return {
      title: 'iOS (Safari / iPhone / iPad)',
      steps: [
        'Tap the Share icon in Safari.',
        "Choose 'Add to Home Screen'.",
        'Open LabPass from the new home screen icon.',
      ],
    };
  }

  if (deferredPrompt) {
    return {
      title: 'Android / Chrome',
      steps: [
        'Tap the "Install App" button below.',
        'Confirm the browser install prompt.',
        'Open LabPass from your home screen or app drawer.',
      ],
    };
  }

  return {
    title: 'Install Instructions',
    steps: [
      'Open your browser menu (usually three dots or a share icon).',
      "Select 'Install app' or 'Add to Home screen'.",
      'Launch LabPass from your home screen once installed.',
    ],
  };
}

export default function InstallGate({ isIOS, deferredPrompt, onInstall }) {
  const hint = getInstallHint(isIOS, deferredPrompt);

  return (
    <main className="install-gate animate-in">
      <section className="install-gate-card">
        <div className="install-gate-brand">
          <img src="/logo.svg" alt="LabPass" className="install-gate-logo" />
          <div>
            <p className="install-gate-kicker">Installation Required</p>
            <h1>LabPass</h1>
          </div>
        </div>

        <p className="install-gate-copy">
          LabPass is a Progressive Web App (PWA). It needs to be installed to keep your accounts secure — browsers can silently clear data in standard tabs after a few days.
        </p>

        {/* Installation Step Panel */}
        <div className="install-gate-panel">
          <h2>{hint.title}</h2>
          <ol className="install-gate-steps">
            {hint.steps.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ol>
          
          {deferredPrompt && !isIOS ? (
            <button className="btn-primary w-full install-gate-btn" onClick={onInstall} style={{ marginTop: '16px' }}>
              Install App
            </button>
          ) : (
            <div className="install-gate-footer" style={{ marginTop: '12px' }}>
              <p>Once installed, LabPass will automatically unlock the setup, scan, and sessions screens.</p>
            </div>
          )}
        </div>

        {/* How to Use PWA Panel */}
        <div className="install-gate-panel" style={{ borderTop: '1px solid var(--line)', paddingTop: '20px', marginTop: '20px' }}>
          <h2>How to use LabPass</h2>
          <ol className="how-to-use-steps" style={{ paddingLeft: '18px', color: 'var(--muted)', fontSize: '0.88rem', lineHeight: '1.6', listStyleType: 'decimal' }}>
            <li style={{ marginBottom: '10px' }}>
              <strong>Continue to Google:</strong> Sign in with Google inside the PWA to save your most used lab computer accounts securely on your device.
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Select Profile:</strong> When you want to sign in at a lab PC, click the <em>"Scan with this account"</em> button on your desired profile.
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Scan QR Code:</strong> Point your camera at the QR code generated by the Lab PC Chrome Extension. The app will automatically open the <strong>back camera</strong> of your phone.
            </li>
            <li style={{ marginBottom: '0' }}>
              <strong>Instant Sign-In:</strong> Once successfully scanned, you will be instantly logged in to the lab computer!
            </li>
          </ol>
        </div>
      </section>
    </main>
  );
}